const { test, after, beforeEach, describe } = require('node:test')
const supertest = require('supertest')
const assert = require('node:assert')
const mongoose = require('mongoose')
const app = require('../app')
const bcrypt = require('bcrypt')
const Child = require('../models/Child')
const User = require('../models/User')